apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
    name: ingress-gateway
    namespace: istio-system
    annotations:
        networking.istio.io/service-type: "ClusterIP"
    labels:
        app: api
        version: v1
        app.kubernetes.io/name: api
        app.kubernetes.io/version: v1
        sidecar.istio.io/inject: "true"
spec:
    gatewayClassName: istio
    listeners:
        - name: http
          port: 80
          protocol: HTTP
          allowedRoutes:
              namespaces:
                  from: All
